# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyscannerSDK', '0004_auto_20161016_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
